[目次に戻る](./README.md)  
[前に戻る](./02.md)  
[次に進む](./04.md)

---

# ブラケット

異なる部品同士をつなぎ合わせるための部品のことである。
今回はブラケットを`3D`プリントする。

## モデル・スケッチの新規作成と軸の投影

これまでと同じ。最初のスケッチは`XZ Plane`でよい。

下図は`X`、`Z`軸の投影が完了した状態。

![2024-06-09_193048](./images/2024-06-09_193048.png)

## ブラケット底面の作成

原点中心に直径`4.5`の真円を描く。

本作品のねじ止めには`M4`ネジを使う。
`3D`プリント部品の場合`0.5mm`程度は大きめの穴を開けた方が上手く組み立てられる。

![2024-06-09_193222.png](./images/2024-06-09_193222.png)

「長方形」をクリックする。

![2024-06-09_193504.png](./images/2024-06-09_193504.png)

円の右上と左下の適当な位置をクリックして長方形を生成し、エンターキーを押す。

![2024-06-09_193631.png](./images/2024-06-09_193631.png)

「対称」を押す。

![2024-06-09_193744.png](./images/2024-06-09_193744.png)

以下の順番で線分をクリックする。

1. 一番上
2. 一番下
3. 水平の軸

要は、対称の中心を最後にクリックすればよい。
水平軸を中心に線対称になるはずである。

![2024-06-09_193901.png](./images/2024-06-09_193901.png)

「寸法」をクリックして、一番上と下の線の間隔を`15`にする。
また、垂直の軸から右端までを`5`左端までを`10`とする。

![2024-06-09_194421.png](./images/2024-06-09_194421.png)

「終了」を押してスケッチ編集を終わる。

![2024-06-09_150047.png](./images/2024-06-09_150047.png)

「押し出し」を使い、厚さ`3mm`の立体にする。

![2024-06-09_194657.png](./images/2024-06-09_194657.png)

## ブラケット側面の作成

立体の上面をクリックしてスケッチを新規作成する。

![2024-06-09_194835.png](./images/2024-06-09_194835.png)

「長方形」をクリックして、既存の長方形の左上隅をクリックし、下辺のどこかを下図のようにクリックする。

![2024-06-09_194949.png](./images/2024-06-09_194949.png)

「寸法」をクリックして、新たに作成した長方形の幅を`3mm`にする。

![2024-06-09_195123.png](./images/2024-06-09_195123.png)

「終了」を押してスケッチ編集を終わる。

![2024-06-09_150047.png](./images/2024-06-09_150047.png)

「押し出し」で立体にする。距離は`12`。

![2024-06-09_195351.png](./images/2024-06-09_195351.png)

側面をクリックしてスケッチを新規作成する。

![2024-06-09_195503.png](./images/2024-06-09_195503.png)

「コンストラクション」をクリックして構築ジオメトリを描画するモードにし、`X Axis`と`Y Axis`をジオメトリ投影する。
これまでと軸が異なるので注意。

![2024-06-09_195628.png](./images/2024-06-09_195628.png)

**「コンストラクション」をクリックして、構築ジオメトリのモードを終了する**

![2024-06-09_142251.png](./images/2024-06-09_142251.png)

`Y`軸上に中心を置く直径`4.5mm`の円を描く。

![2024-06-09_195821.png](./images/2024-06-09_195821.png)

寸法を使い、長方形の下辺から円中心までの距離を`10`にする。

![2024-06-09_200016.png](./images/2024-06-09_200016.png)

「終了」を押してスケッチ編集を終わる。

![2024-06-09_150047.png](./images/2024-06-09_150047.png)

押し出しを使い、穴を開ける。

これまでと異なり「ブール演算」で差演算を選択することで穴を開けられる。

![2024-06-09_200253.png](./images/2024-06-09_200253.png)

## フィレットを加える

「フィレット」をクリックする。

![2024-06-09_190834.png](./images/2024-06-09_190834.png)

詳細は前項を参照。半径は好みで決めてよい。下図は`2mm`。
強度を増すために、角の内側にフィレットをかけて厚くしている。

![2024-06-09_200549.png](./images/2024-06-09_200549.png)

## ファイル保存と3Dプリント用ファイルの出力

前項を参照し、パーツを「ドキュメント」の`Inventor`フォルダに`lecture_cad_03.ipt`というファイル名で保存する。

次に、「ファイル」から「エクスポート」、「`CAD`形式」をクリックする。

![2024-06-09_200802.png](./images/2024-06-09_200802.png)

保存形式に`*.stl`を選択しファイル名を`lecture_cad_03.stl`としてエクスポートする。

![2024-06-09_201003.png](./images/2024-06-09_201003.png)

---

[目次に戻る](./README.md)  
[前に戻る](./02.md)  
[次に進む](./04.md)
